import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    categories: {
      All: 'All', Restaurant: 'Restaurant', 'Food Truck': 'Food Truck',
      Bar: 'Bar', Cafe: 'Cafe', Shop: 'Shop', Service: 'Service',
      Beach: 'Beach', Park: 'Park', Attraction: 'Attraction', Other: 'Other', Closed: 'Closed',
    },
    noBusinesses: 'No businesses yet.',
    addYours: 'Add yours!',
    addBusiness: 'Add your Business',
    login: 'Login',
    myBusiness: 'My Business',
    logout: 'Logout',
    dashboard: 'Dashboard',
    navSubtitle: "What's open in Vieques?",

    loginPage: {
      subtitle: 'Sign in to manage your business',
      ownerTab: 'Business Owner',
      adminTab: 'Admin',
      codeTitle: 'Enter your business code',
      codeLabel: 'Business Code',
      codeHint: '3-character code given when you registered',
      checking: 'Checking…',
      loginBtn: 'Login →',
      forgotCode: 'Forgot your code?',
      forgotTitle: 'Forgot your code?',
      forgotSubtitle: "Send a message to the admin and they'll get back to you.",
      bizNameLabel: 'Your Business Name',
      msgLabel: 'Message',
      msgOptional: '(optional)',
      msgPlaceholder: 'Any details that help us find your account…',
      sending: 'Sending…',
      sendBtn: 'Send Message →',
      backToLogin: 'Back to Login',
      sentTitle: 'Message sent!',
      sentBody: 'The admin will reach out with your code shortly.',
      adminTitle: 'Admin Login',
      usernameLabel: 'Username',
      passwordLabel: 'Password',
      signingIn: 'Signing in…',
      signInBtn: 'Sign In →',
    },

    owner: {
      updateStatusTitle: 'Update Status',
      noteLabel: 'Note',
      noteOptional: '(optional)',
      notePlaceholder: 'e.g. Fresh catch today, closing at 6pm…',
      saving: 'Saving…',
      updateBtn: 'Update Status',
      statusUpdated: 'Status updated!',
      photosTitle: 'Photos',
      hoursTitle: 'Business Hours',
      hoursHint: 'Once hours are set, your open/closed status updates automatically. Use the status panel above for overrides.',
      infoTitle: 'Business Info',
      edit: 'Edit',
      cancel: 'Cancel',
      categoryLabel: 'Category',
      nameLabel: 'Name',
      descLabel: 'Description',
      phoneLabel: 'WhatsApp / SMS number',
      phoneHint: 'Text OPEN, CLOSED, LUNCH, or SEASON to your Abierto number to update status instantly.',
      noPhone: 'No phone linked — add your number to update status by text',
      useLocation: '📍 Use Current Location',
      saveChanges: 'Save Changes',
      autoHours: 'Open/Closed is set automatically from your hours.',
      backAt: 'Back at',
      reopening: 'Reopening',
      shownAs: 'Shown as: "Back at {time}" — auto-clears when time passes',
    },

    businessPage: {
      hoursTitle: 'Hours',
      backAll: '← All Businesses',
      notFound: 'Business not found.',
      back: '← Back',
      backAt: 'Back at',
      reopening: 'Reopening',
      updated: 'Updated',
      reportBtn: 'Report wrong info',
      reportTitle: 'Report Wrong Info',
      reportSubtitle: 'Help us keep Abierto accurate. We\'ll look into it right away.',
      reportIssue1: 'Marked as open but is actually closed',
      reportIssue2: 'Marked as closed but is actually open',
      reportIssue3: 'Hours listed are incorrect',
      reportIssue4: 'Other inaccuracy',
      reportNote: 'Additional details (optional)',
      reportNotePlaceholder: 'Anything else we should know…',
      reportSend: 'Send Report',
      reportSending: 'Sending…',
      reportDone: 'Thanks — we\'ll look into it!',
      reportCancel: 'Cancel',
    },

    notFound: {
      title: 'Page not found',
      subtitle: 'Drifted off the map.',
      back: 'Back to Abierto',
    },

    register: {
      title: 'Add Your Business',
      subtitle: "Get listed on Abierto and let Vieques know when you're open.",
      accuracyTitle: 'Accuracy is everything.',
      accuracyBody: "Abierto exists so visitors and neighbors know exactly when you're open — not just that you exist. False hours hurt your customers and your reputation. If your status is wrong, people will report it. Update when things change and this works for everyone.",
      sectionInfo: 'Business Info',
      labelName: 'Business Name',
      placeholderName: 'e.g. Playa Snacks',
      labelCategory: 'Category',
      placeholderCategory: 'Select a category…',
      labelDescription: 'Description',
      placeholderDescription: 'Tell customers what you offer…',
      labelPhone: 'Phone / WhatsApp',
      phoneOptional: '(optional)',
      placeholderPhone: '(787) 000-0000',
      sectionLocation: 'Location',
      locationHint: 'Used to pin your business on the map. Great for food trucks and mobile stands.',
      btnLocate: '📍 Use My Current Location',
      btnLocating: 'Getting location…',
      btnTryAgain: 'Try Again',
      labelLat: 'Latitude',
      labelLon: 'Longitude',
      btnSubmit: 'Register Business →',
      btnSubmitting: 'Registering…',
      errName: 'Business name is required.',
      errLocation: 'Could not get location. Enter manually.',
      errLocationDenied: 'Location access is blocked.',
      errLocationDeniedHint: 'To use this feature, enable location in your browser or device settings, then tap Try Again.',
    },

    success: {
      title: "You're on Abierto!",
      subtitle: "is now listed. Here's your login code:",
      tapCopy: 'Tap to copy',
      copied: '✅ Copied!',
      warning: '⚠️ Save this code now.',
      warningBody: 'This is the only way to log in to your business. Screenshot it or write it down. It cannot be recovered if lost.',
      btnDashboard: 'Go to My Dashboard →',
      btnLoading: 'Loading…',
      btnHome: 'Back to Home',
    },
  },

  es: {
    categories: {
      All: 'Todo', Restaurant: 'Restaurante', 'Food Truck': 'Food Truck',
      Bar: 'Bar', Cafe: 'Café', Shop: 'Tienda', Service: 'Servicio',
      Beach: 'Playa', Park: 'Parque', Attraction: 'Atracción', Other: 'Otro', Closed: 'Cerrado',
    },
    noBusinesses: 'No hay negocios todavía.',
    addYours: '¡Añade el tuyo!',
    addBusiness: 'Añade tu Negocio',
    login: 'Entrar',
    myBusiness: 'Mi Negocio',
    logout: 'Salir',
    dashboard: 'Panel',
    navSubtitle: '¿Qué está abierto en Vieques?',

    loginPage: {
      subtitle: 'Inicia sesión para gestionar tu negocio',
      ownerTab: 'Dueño de Negocio',
      adminTab: 'Admin',
      codeTitle: 'Ingresa tu código de negocio',
      codeLabel: 'Código de Negocio',
      codeHint: 'Código de 3 caracteres dado al registrarte',
      checking: 'Verificando…',
      loginBtn: 'Entrar →',
      forgotCode: '¿Olvidaste tu código?',
      forgotTitle: '¿Olvidaste tu código?',
      forgotSubtitle: 'Envía un mensaje al administrador y te contactarán.',
      bizNameLabel: 'Nombre de tu Negocio',
      msgLabel: 'Mensaje',
      msgOptional: '(opcional)',
      msgPlaceholder: 'Detalles que nos ayuden a encontrar tu cuenta…',
      sending: 'Enviando…',
      sendBtn: 'Enviar Mensaje →',
      backToLogin: 'Volver al inicio',
      sentTitle: '¡Mensaje enviado!',
      sentBody: 'El administrador te contactará con tu código pronto.',
      adminTitle: 'Inicio de Sesión Admin',
      usernameLabel: 'Usuario',
      passwordLabel: 'Contraseña',
      signingIn: 'Iniciando sesión…',
      signInBtn: 'Iniciar Sesión →',
    },

    owner: {
      updateStatusTitle: 'Actualizar Estado',
      noteLabel: 'Nota',
      noteOptional: '(opcional)',
      notePlaceholder: 'ej. Pesca fresca hoy, cerramos a las 6pm…',
      saving: 'Guardando…',
      updateBtn: 'Actualizar Estado',
      statusUpdated: '¡Estado actualizado!',
      photosTitle: 'Fotos',
      hoursTitle: 'Horario de Negocio',
      hoursHint: 'Una vez configurado el horario, tu estado se actualiza automáticamente. Usa el panel de arriba para cambios manuales.',
      infoTitle: 'Info del Negocio',
      edit: 'Editar',
      cancel: 'Cancelar',
      categoryLabel: 'Categoría',
      nameLabel: 'Nombre',
      descLabel: 'Descripción',
      phoneLabel: 'Número WhatsApp / SMS',
      phoneHint: 'Envía OPEN, CLOSED, LUNCH o SEASON a tu número de Abierto para actualizar el estado al instante.',
      noPhone: 'Sin teléfono — agrega tu número para actualizar por mensaje',
      useLocation: '📍 Usar Ubicación Actual',
      saveChanges: 'Guardar Cambios',
      autoHours: 'Abierto/Cerrado se configura automáticamente según tu horario.',
      backAt: 'Regresa a las',
      reopening: 'Reabre el',
      shownAs: 'Se mostrará: "Regresa a las {time}" — se borra automáticamente',
    },

    businessPage: {
      hoursTitle: 'Horario',
      backAll: '← Todos los Negocios',
      notFound: 'Negocio no encontrado.',
      back: '← Atrás',
      backAt: 'Regresa a las',
      reopening: 'Reabre el',
      updated: 'Actualizado',
      reportBtn: 'Reportar info incorrecta',
      reportTitle: 'Reportar Info Incorrecta',
      reportSubtitle: 'Ayúdanos a mantener Abierto actualizado. Lo revisaremos de inmediato.',
      reportIssue1: 'Marcado como abierto pero está cerrado',
      reportIssue2: 'Marcado como cerrado pero está abierto',
      reportIssue3: 'El horario está incorrecto',
      reportIssue4: 'Otra inexactitud',
      reportNote: 'Detalles adicionales (opcional)',
      reportNotePlaceholder: 'Algo más que debamos saber…',
      reportSend: 'Enviar Reporte',
      reportSending: 'Enviando…',
      reportDone: '¡Gracias — lo revisaremos!',
      reportCancel: 'Cancelar',
    },

    notFound: {
      title: 'Página no encontrada',
      subtitle: 'Te alejaste del mapa.',
      back: 'Volver a Abierto',
    },

    register: {
      title: 'Añade tu Negocio',
      subtitle: 'Regístrate en Abierto y dile a Vieques cuándo estás abierto.',
      accuracyTitle: 'La exactitud lo es todo.',
      accuracyBody: 'Abierto existe para que visitantes y vecinos sepan exactamente cuándo estás abierto — no solo que existes. Un horario falso perjudica a tus clientes y a tu reputación. Si tu estado está incorrecto, la gente lo reportará. Actualiza cuando algo cambie y esto funciona para todos.',
      sectionInfo: 'Info del Negocio',
      labelName: 'Nombre del Negocio',
      placeholderName: 'ej. Playa Snacks',
      labelCategory: 'Categoría',
      placeholderCategory: 'Selecciona una categoría…',
      labelDescription: 'Descripción',
      placeholderDescription: '¿Qué ofreces a tus clientes?',
      labelPhone: 'Teléfono / WhatsApp',
      phoneOptional: '(opcional)',
      placeholderPhone: '(787) 000-0000',
      sectionLocation: 'Ubicación',
      locationHint: 'Para ubicar tu negocio en el mapa. Ideal para food trucks y puestos móviles.',
      btnLocate: '📍 Usar Mi Ubicación Actual',
      btnLocating: 'Obteniendo ubicación…',
      btnTryAgain: 'Intentar de Nuevo',
      labelLat: 'Latitud',
      labelLon: 'Longitud',
      btnSubmit: 'Registrar Negocio →',
      btnSubmitting: 'Registrando…',
      errName: 'El nombre del negocio es obligatorio.',
      errLocation: 'No se pudo obtener la ubicación. Ingrésala manualmente.',
      errLocationDenied: 'El acceso a la ubicación está bloqueado.',
      errLocationDeniedHint: 'Para usar esta función, habilita la ubicación en la configuración de tu navegador o dispositivo, y luego toca Intentar de Nuevo.',
    },

    success: {
      title: '¡Ya estás en Abierto!',
      subtitle: 'ya está registrado. Tu código de acceso:',
      tapCopy: 'Toca para copiar',
      copied: '✅ ¡Copiado!',
      warning: '⚠️ Guarda este código ahora.',
      warningBody: 'Es la única forma de acceder a tu negocio. Tómale una captura o escríbelo. No se puede recuperar si se pierde.',
      btnDashboard: 'Ir a Mi Panel →',
      btnLoading: 'Cargando…',
      btnHome: 'Volver al Inicio',
    },
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('abierto_lang') || 'en');

  const toggle = () => {
    const next = lang === 'en' ? 'es' : 'en';
    localStorage.setItem('abierto_lang', next);
    setLang(next);
  };

  return (
    <LangContext.Provider value={{ lang, t: translations[lang], toggle }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
